# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Elastic_Block_Store(_AWS):
    _type = "storage/elastic_block_store"
    _icon_dir = "resources/aws/storage/elastic_block_store"


class MultipleVolumes(_Elastic_Block_Store):
    _icon = "multiple-volumes.png"
class Snapshot(_Elastic_Block_Store):
    _icon = "snapshot.png"
class Volume(_Elastic_Block_Store):
    _icon = "volume.png"

# Aliases
