# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Analytics(_AWS):
    _type = "analytics"
    _icon_dir = "resources/aws/analytics"


class Athena(_Analytics):
    _icon = "athena.png"
class Cloudsearch(_Analytics):
    _icon = "cloudsearch.png"
class DataExchange(_Analytics):
    _icon = "data-exchange.png"
class DataPipeline(_Analytics):
    _icon = "data-pipeline.png"
class ElasticsearchService(_Analytics):
    _icon = "elasticsearch-service.png"
class EMR(_Analytics):
    _icon = "emr.png"
class Glue(_Analytics):
    _icon = "glue.png"
class KinesisDataAnalytics(_Analytics):
    _icon = "kinesis-data-analytics.png"
class KinesisDataStreams(_Analytics):
    _icon = "kinesis-data-streams.png"
class KinesisFirehose(_Analytics):
    _icon = "kinesis-firehose.png"
class KinesisVideoStreams(_Analytics):
    _icon = "kinesis-video-streams.png"
class Kinesis(_Analytics):
    _icon = "kinesis.png"
class LakeFormation(_Analytics):
    _icon = "lake-formation.png"
class ManagedStreamingForKafka(_Analytics):
    _icon = "managed-streaming-for-kafka.png"
class Quicksight(_Analytics):
    _icon = "quicksight.png"
class Redshiftct(_Analytics):
    _icon = "redshiftct.png"

# Aliases

ES = ElasticsearchService