# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Cloudwatch(_AWS):
    _type = "management/cloudwatch"
    _icon_dir = "resources/aws/management/cloudwatch"


class Alarm(_Cloudwatch):
    _icon = "alarm.png"
class EventBased(_Cloudwatch):
    _icon = "event-based.png"
class EventTimeBased(_Cloudwatch):
    _icon = "event-time-based.png"
class Logs(_Cloudwatch):
    _icon = "logs.png"
class Rule(_Cloudwatch):
    _icon = "rule.png"

# Aliases
