# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Security(_AWS):
    _type = "security"
    _icon_dir = "resources/aws/security"


class Artifact(_Security):
    _icon = "artifact.png"
class CertificateManager(_Security):
    _icon = "certificate-manager.png"
class CloudDirectory(_Security):
    _icon = "cloud-directory.png"
class Cloudhsm(_Security):
    _icon = "cloudhsm.png"
class Cognito(_Security):
    _icon = "cognito.png"
class Detective(_Security):
    _icon = "detective.png"
class DirectoryService(_Security):
    _icon = "directory-service.png"
class FirewallManager(_Security):
    _icon = "firewall-manager.png"
class Guardduty(_Security):
    _icon = "guardduty.png"
class IdentityAndAccessManagement(_Security):
    _icon = "identity-and-access-management.png"
class Inspector(_Security):
    _icon = "inspector.png"
class KeyManagementServices(_Security):
    _icon = "key-management-services.png"
class Macie(_Security):
    _icon = "macie.png"
class ResourcesAccessManager(_Security):
    _icon = "resources-access-manager.png"
class SecretsManager(_Security):
    _icon = "secrets-manager.png"
class SecurityHub(_Security):
    _icon = "security-hub.png"
class Shield(_Security):
    _icon = "shield.png"
class SingleSignOn(_Security):
    _icon = "single-sign-on.png"
class WAF(_Security):
    _icon = "waf.png"

# Aliases

ACM = CertificateManager
CloudHSM = Cloudhsm
DS = DirectoryService
FMS = FirewallManager
IAM = IdentityAndAccessManagement
KMS = KeyManagementServices
RAM = ResourcesAccessManager