# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _App_Mesh(_AWS):
    _type = "network/app_mesh"
    _icon_dir = "resources/aws/network/app_mesh"


class VirtualGateway(_App_Mesh):
    _icon = "virtual-gateway.png"

# Aliases
