# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _S3_Glacier(_AWS):
    _type = "storage/s3_glacier"
    _icon_dir = "resources/aws/storage/s3_glacier"


class Archive(_S3_Glacier):
    _icon = "archive.png"
class Vault(_S3_Glacier):
    _icon = "vault.png"

# Aliases
