# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Devtools(_AWS):
    _type = "devtools"
    _icon_dir = "resources/aws/devtools"


class CloudDevelopmentKit(_Devtools):
    _icon = "cloud-development-kit.png"
class Cloud9(_Devtools):
    _icon = "cloud9.png"
class Codeartifact(_Devtools):
    _icon = "codeartifact.png"
class Codebuild(_Devtools):
    _icon = "codebuild.png"
class Codecommit(_Devtools):
    _icon = "codecommit.png"
class Codedeploy(_Devtools):
    _icon = "codedeploy.png"
class Codepipeline(_Devtools):
    _icon = "codepipeline.png"
class Codestar(_Devtools):
    _icon = "codestar.png"
class CommandLineInterface(_Devtools):
    _icon = "command-line-interface.png"
class ToolsAndSDK(_Devtools):
    _icon = "tools-and-sdk.png"
class XRay(_Devtools):
    _icon = "x-ray.png"

# Aliases

CLI = CommandLineInterface