# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Inspector(_AWS):
    _type = "security/inspector"
    _icon_dir = "resources/aws/security/inspector"


class Agent(_Inspector):
    _icon = "agent.png"

# Aliases
