# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Elastic_Beanstalk(_AWS):
    _type = "compute/elastic_beanstalk"
    _icon_dir = "resources/aws/compute/elastic_beanstalk"


class Application(_Elastic_Beanstalk):
    _icon = "application.png"
class Deployment(_Elastic_Beanstalk):
    _icon = "deployment.png"

# Aliases
