# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Cloudsearch(_AWS):
    _type = "analytics/cloudsearch"
    _icon_dir = "resources/aws/analytics/cloudsearch"


class SearchDocuments(_Cloudsearch):
    _icon = "search-documents.png"

# Aliases
