# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Rekognition(_AWS):
    _type = "ml/rekognition"
    _icon_dir = "resources/aws/ml/rekognition"


class Image(_Rekognition):
    _icon = "image.png"
class Video(_Rekognition):
    _icon = "video.png"

# Aliases
