# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Simple_Email_Service(_AWS):
    _type = "engagement/simple_email_service"
    _icon_dir = "resources/aws/engagement/simple_email_service"


class Email(_Simple_Email_Service):
    _icon = "email.png"

# Aliases
