# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Network(_AWS):
    _type = "network"
    _icon_dir = "resources/aws/network"


class APIGateway(_Network):
    _icon = "api-gateway.png"
class AppMeshMesh(_Network):
    _icon = "app-mesh-mesh.png"
class AppMeshVirtualNode(_Network):
    _icon = "app-mesh-virtual-node.png"
class AppMeshVirtualRouter(_Network):
    _icon = "app-mesh-virtual-router.png"
class AppMeshVirtualService(_Network):
    _icon = "app-mesh-virtual-service.png"
class AppMesh(_Network):
    _icon = "app-mesh.png"
class CloudDirectory(_Network):
    _icon = "cloud-directory.png"
class CloudMapNamespace(_Network):
    _icon = "cloud-map-namespace.png"
class CloudMapResource(_Network):
    _icon = "cloud-map-resource.png"
class CloudFront(_Network):
    _icon = "cloudfront.png"
class Cloudmap(_Network):
    _icon = "cloudmap.png"
class DirectConnectGateway(_Network):
    _icon = "direct-connect-gateway.png"
class DirectConnect(_Network):
    _icon = "direct-connect.png"
class ElasticLoadBalancing(_Network):
    _icon = "elastic-load-balancing.png"
class GlobalAccelerator(_Network):
    _icon = "global-accelerator.png"
class Privatelink(_Network):
    _icon = "privatelink.png"
class Route53HostedZone(_Network):
    _icon = "route-53-hosted-zone.png"
class Route53(_Network):
    _icon = "route-53.png"
class SiteToSiteVpn(_Network):
    _icon = "site-to-site-vpn.png"
class TransitGateway(_Network):
    _icon = "transit-gateway.png"
class VirtualPrivateCloud(_Network):
    _icon = "virtual-private-cloud.png"
class Vpn(_Network):
    _icon = "vpn.png"

# Aliases

CF = CloudFront
ELB = ElasticLoadBalancing
GAX = GlobalAccelerator
VPC = VirtualPrivateCloud