# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Media(_AWS):
    _type = "media"
    _icon_dir = "resources/aws/media"


class ElasticTranscoder(_Media):
    _icon = "elastic-transcoder.png"
class ElementalAppliancesAndSoftware(_Media):
    _icon = "elemental-appliances-and-software.png"
class ElementalLink(_Media):
    _icon = "elemental-link.png"
class ElementalMediaconnect(_Media):
    _icon = "elemental-mediaconnect.png"
class ElementalMediaconvert(_Media):
    _icon = "elemental-mediaconvert.png"
class ElementalMedialive(_Media):
    _icon = "elemental-medialive.png"
class ElementalMediapackage(_Media):
    _icon = "elemental-mediapackage.png"
class ElementalMediastore(_Media):
    _icon = "elemental-mediastore.png"
class ElementalMediatailor(_Media):
    _icon = "elemental-mediatailor.png"
class InteractiveVideo(_Media):
    _icon = "interactive-video.png"
class KinesisVideoStreams(_Media):
    _icon = "kinesis-video-streams.png"

# Aliases
