# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Storage_Gateway(_AWS):
    _type = "storage/storage_gateway"
    _icon_dir = "resources/aws/storage/storage_gateway"


class CachedVolume(_Storage_Gateway):
    _icon = "cached-volume.png"
class FileGateway(_Storage_Gateway):
    _icon = "file-gateway.png"
class NonCachedVolume(_Storage_Gateway):
    _icon = "non-cached-volume.png"
class TapeGateway(_Storage_Gateway):
    _icon = "tape-gateway.png"
class VirtualTapeLibrary(_Storage_Gateway):
    _icon = "virtual-tape-library.png"
class VolumeGateway(_Storage_Gateway):
    _icon = "volume-gateway.png"

# Aliases
