# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Api_Gateway(_AWS):
    _type = "network/api_gateway"
    _icon_dir = "resources/aws/network/api_gateway"


class Endpoint(_Api_Gateway):
    _icon = "endpoint.png"

# Aliases
