# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _OpenStack

class _Billing(_OpenStack):
    _type = "operations/billing"
    _icon_dir = "resources/openstack/operations/billing"


class Cloudkitty(_Billing):
    _icon = "cloudkitty.png"

# Aliases
