# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _EC2(_AWS):
    _type = "compute/ec2"
    _icon_dir = "resources/aws/compute/ec2"


class A1Instance(_EC2):
    _icon = "a1-instance.png"
class AutoScaling(_EC2):
    _icon = "auto-scaling.png"
class C4Instance(_EC2):
    _icon = "c4-instance.png"
class C5Instance(_EC2):
    _icon = "c5-instance.png"
class C5NInstance(_EC2):
    _icon = "c5n-instance.png"
class C6GInstance(_EC2):
    _icon = "c6g-instance.png"
class D2Instance(_EC2):
    _icon = "d2-instance.png"
class DbInstance(_EC2):
    _icon = "db-instance.png"
class ElasticIpAddress(_EC2):
    _icon = "elastic-ip-address.png"
class F1Instance(_EC2):
    _icon = "f1-instance.png"
class G3Instance(_EC2):
    _icon = "g3-instance.png"
class H1Instance(_EC2):
    _icon = "h1-instance.png"
class HmiInstance(_EC2):
    _icon = "hmi-instance.png"
class I3Instance(_EC2):
    _icon = "i3-instance.png"
class Inferentia(_EC2):
    _icon = "inferentia.png"
class InstanceWithCloudwatch(_EC2):
    _icon = "instance-with-cloudwatch.png"
class Instance(_EC2):
    _icon = "instance.png"
class Instances(_EC2):
    _icon = "instances.png"
class M4Instance(_EC2):
    _icon = "m4-instance.png"
class M5Instance(_EC2):
    _icon = "m5-instance.png"
class M5AInstance(_EC2):
    _icon = "m5a-instance.png"
class M5NInstance(_EC2):
    _icon = "m5n-instance.png"
class M6GInstance(_EC2):
    _icon = "m6g-instance.png"
class P2Instance(_EC2):
    _icon = "p2-instance.png"
class P3Instance(_EC2):
    _icon = "p3-instance.png"
class R4Instance(_EC2):
    _icon = "r4-instance.png"
class R5Instance(_EC2):
    _icon = "r5-instance.png"
class R5AInstance(_EC2):
    _icon = "r5a-instance.png"
class R5NInstance(_EC2):
    _icon = "r5n-instance.png"
class R6GInstance(_EC2):
    _icon = "r6g-instance.png"
class Rescue(_EC2):
    _icon = "rescue.png"
class SpotInstance(_EC2):
    _icon = "spot-instance.png"
class T2Instance(_EC2):
    _icon = "t2-instance.png"
class T3Instance(_EC2):
    _icon = "t3-instance.png"
class X1Instance(_EC2):
    _icon = "x1-instance.png"
class X1EInstance(_EC2):
    _icon = "x1e-instance.png"
class Z1DInstance(_EC2):
    _icon = "z1d-instance.png"

# Aliases
