# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Fire(_AWS):
    _type = "iot/iot/fire"
    _icon_dir = "resources/aws/iot/iot/fire"


class Tv(_Fire):
    _icon = "tv.png"

# Aliases
