# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Simple_Notification_Service(_AWS):
    _type = "integration/simple_notification_service"
    _icon_dir = "resources/aws/integration/simple_notification_service"


class EmailNotification(_Simple_Notification_Service):
    _icon = "email-notification.png"
class HttpNotification(_Simple_Notification_Service):
    _icon = "http-notification.png"
class Topic(_Simple_Notification_Service):
    _icon = "topic.png"

# Aliases
