# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Snowball(_AWS):
    _type = "storage/snowball"
    _icon_dir = "resources/aws/storage/snowball"


class SnowballImportExport(_Snowball):
    _icon = "snowball-import-export.png"

# Aliases
