# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Certificate_Manager(_AWS):
    _type = "security/certificate_manager"
    _icon_dir = "resources/aws/security/certificate_manager"


class CertificateAuthority(_Certificate_Manager):
    _icon = "certificate-authority.png"

# Aliases
