# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Fire_Tv(_AWS):
    _type = "iot/iot/fire_tv"
    _icon_dir = "resources/aws/iot/iot/fire_tv"


class Stick(_Fire_Tv):
    _icon = "stick.png"

# Aliases
