# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Elasticache(_AWS):
    _type = "database/elasticache"
    _icon_dir = "resources/aws/database/elasticache"


class CacheNode(_Elasticache):
    _icon = "cache-node.png"
class ElasticacheForMemcached(_Elasticache):
    _icon = "elasticache-for-memcached.png"
class ElasticacheForRedis(_Elasticache):
    _icon = "elasticache-for-redis.png"

# Aliases
