# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _CloudFront(_AWS):
    _type = "network/cloudfront"
    _icon_dir = "resources/aws/network/cloudfront"


class DownloadDistribution(_CloudFront):
    _icon = "download-distribution.png"
class EdgeLocation(_CloudFront):
    _icon = "edge-location.png"
class StreamingDistribution(_CloudFront):
    _icon = "streaming-distribution.png"

# Aliases
