# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Iot_Thing(_AWS):
    _type = "iot/iot_thing"
    _icon_dir = "resources/aws/iot/iot_thing"


class Bank(_Iot_Thing):
    _icon = "bank.png"
class Bicycle(_Iot_Thing):
    _icon = "bicycle.png"
class Camera(_Iot_Thing):
    _icon = "camera.png"
class Car(_Iot_Thing):
    _icon = "car.png"
class Cart(_Iot_Thing):
    _icon = "cart.png"
class CoffeePot(_Iot_Thing):
    _icon = "coffee-pot.png"
class DoorLock(_Iot_Thing):
    _icon = "door-lock.png"
class Factory(_Iot_Thing):
    _icon = "factory.png"
class Generic(_Iot_Thing):
    _icon = "generic.png"
class House(_Iot_Thing):
    _icon = "house.png"
class Lightbulb(_Iot_Thing):
    _icon = "lightbulb.png"
class MedicalEmergency(_Iot_Thing):
    _icon = "medical-emergency.png"
class PoliceEmergency(_Iot_Thing):
    _icon = "police-emergency.png"
class Thermostat(_Iot_Thing):
    _icon = "thermostat.png"
class Travel(_Iot_Thing):
    _icon = "travel.png"
class Utility(_Iot_Thing):
    _icon = "utility.png"
class Windfarm(_Iot_Thing):
    _icon = "windfarm.png"

# Aliases
