# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Iot_Mqtt(_AWS):
    _type = "iot/iot_mqtt"
    _icon_dir = "resources/aws/iot/iot_mqtt"


class Protocol(_Iot_Mqtt):
    _icon = "protocol.png"

# Aliases
