# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Ami(_AWS):
    _type = "compute/ec2/ami"
    _icon_dir = "resources/aws/compute/ec2/ami"


class Resource(_Ami):
    _icon = "resource.png"

# Aliases
