# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Identity_Access_Management(_AWS):
    _type = "security/identity_access_management"
    _icon_dir = "resources/aws/security/identity_access_management"


class AddOn(_Identity_Access_Management):
    _icon = "add-on.png"
class DataEncryptionKey(_Identity_Access_Management):
    _icon = "data-encryption-key.png"
class EncryptedData(_Identity_Access_Management):
    _icon = "encrypted-data.png"
class IamAccessAnalyzer(_Identity_Access_Management):
    _icon = "iam-access-analyzer.png"
class LongTermSecurityCredential(_Identity_Access_Management):
    _icon = "long-term-security-credential.png"
class MfaToken(_Identity_Access_Management):
    _icon = "mfa-token.png"
class Permissions(_Identity_Access_Management):
    _icon = "permissions.png"
class Role(_Identity_Access_Management):
    _icon = "role.png"
class StsAlternate(_Identity_Access_Management):
    _icon = "sts-alternate.png"
class Sts(_Identity_Access_Management):
    _icon = "sts.png"
class TemporarySecurityCredential(_Identity_Access_Management):
    _icon = "temporary-security-credential.png"

# Aliases
