# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Cloud_Map(_AWS):
    _type = "network/cloud_map"
    _icon_dir = "resources/aws/network/cloud_map"


class Service(_Cloud_Map):
    _icon = "service.png"

# Aliases
