# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Route_53(_AWS):
    _type = "network/route_53"
    _icon_dir = "resources/aws/network/route_53"


class RouteTable(_Route_53):
    _icon = "route-table.png"

# Aliases
