# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Iot_Greengrass(_AWS):
    _type = "iot/iot_greengrass"
    _icon_dir = "resources/aws/iot/iot_greengrass"


class Connector(_Iot_Greengrass):
    _icon = "connector.png"

# Aliases
