# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Datasync(_AWS):
    _type = "migration/datasync"
    _icon_dir = "resources/aws/migration/datasync"


class Agent(_Datasync):
    _icon = "agent.png"

# Aliases
