# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class __Lambda(_AWS):
    _type = "iot/iot/_lambda"
    _icon_dir = "resources/aws/iot/iot/_lambda"


class Function(__Lambda):
    _icon = "function.png"

# Aliases
