# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Elastic_File_System(_AWS):
    _type = "storage/elastic_file_system"
    _icon_dir = "resources/aws/storage/elastic_file_system"


class FileSystem(_Elastic_File_System):
    _icon = "file-system.png"

# Aliases
