# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Directory_Service(_AWS):
    _type = "security/directory_service"
    _icon_dir = "resources/aws/security/directory_service"


class AdConnector(_Directory_Service):
    _icon = "ad-connector.png"
class ManagedMicrosoftAd(_Directory_Service):
    _icon = "managed-microsoft-ad.png"
class SimpleAd(_Directory_Service):
    _icon = "simple-ad.png"

# Aliases
