# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Containers(_AWS):
    _type = "containers"
    _icon_dir = "resources/aws/containers"


class ElasticContainerKubernetes(_Containers):
    _icon = "elastic-container-kubernetes.png"
class ElasticContainerRegistry(_Containers):
    _icon = "elastic-container-registry.png"
class ElasticContainerService(_Containers):
    _icon = "elastic-container-service.png"
class Fargate(_Containers):
    _icon = "fargate.png"

# Aliases
