# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Storage(_AWS):
    _type = "storage"
    _icon_dir = "resources/aws/storage"


class Backup(_Storage):
    _icon = "backup.png"
class CloudendureDisasterRecovery(_Storage):
    _icon = "cloudendure-disaster-recovery.png"
class ElasticBlockStore(_Storage):
    _icon = "elastic-block-store.png"
class ElasticFileSystem(_Storage):
    _icon = "elastic-file-system.png"
class FsxForLustre(_Storage):
    _icon = "fsx-for-lustre.png"
class FsxForWfs(_Storage):
    _icon = "fsx-for-wfs.png"
class Fsx(_Storage):
    _icon = "fsx.png"
class Glacier(_Storage):
    _icon = "glacier.png"
class InfrequentAccessStorageClass(_Storage):
    _icon = "infrequent-access-storage-class.png"
class S3Standard(_Storage):
    _icon = "s3-standard.png"
class SnowballEdge(_Storage):
    _icon = "snowball-edge.png"
class Snowball(_Storage):
    _icon = "snowball.png"
class Snowcone(_Storage):
    _icon = "snowcone.png"
class Snowmobile(_Storage):
    _icon = "snowmobile.png"
class StandardStorageClass(_Storage):
    _icon = "standard-storage-class.png"
class StorageGateway(_Storage):
    _icon = "storage-gateway.png"

# Aliases

CDR = CloudendureDisasterRecovery
EBS = ElasticBlockStore
EFS = ElasticFileSystem
S3 = S3Standard