# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Redshift(_AWS):
    _type = "database/redshift"
    _icon_dir = "resources/aws/database/redshift"


class DenseComputeNode(_Redshift):
    _icon = "dense-compute-node.png"
class DenseStorageNode(_Redshift):
    _icon = "dense-storage-node.png"

# Aliases
