# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Managed_Blockchain(_AWS):
    _type = "blockchain/managed_blockchain"
    _icon_dir = "resources/aws/blockchain/managed_blockchain"


class Blockchain(_Managed_Blockchain):
    _icon = "blockchain.png"

# Aliases
