# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Iot_Analytics(_AWS):
    _type = "iot/iot_analytics"
    _icon_dir = "resources/aws/iot/iot_analytics"


class Channel(_Iot_Analytics):
    _icon = "channel.png"
class DataSet(_Iot_Analytics):
    _icon = "data-set.png"
class DataStore(_Iot_Analytics):
    _icon = "data-store.png"
class Notebook(_Iot_Analytics):
    _icon = "notebook.png"
class Pipeline(_Iot_Analytics):
    _icon = "pipeline.png"

# Aliases
