# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _VPC(_AWS):
    _type = "network/vpc"
    _icon_dir = "resources/aws/network/vpc"


class CustomerGateway(_VPC):
    _icon = "customer-gateway.png"
class ElasticNetworkAdapter(_VPC):
    _icon = "elastic-network-adapter.png"
class ElasticNetworkInterface(_VPC):
    _icon = "elastic-network-interface.png"
class Endpoints(_VPC):
    _icon = "endpoints.png"
class FlowLogs(_VPC):
    _icon = "flow-logs.png"
class InternetGateway(_VPC):
    _icon = "internet-gateway.png"
class NATGateway(_VPC):
    _icon = "nat-gateway.png"
class NetworkAccessControlList(_VPC):
    _icon = "network-access-control-list.png"
class PeeringConnection(_VPC):
    _icon = "peering-connection.png"
class Router(_VPC):
    _icon = "router.png"
class TrafficMirroring(_VPC):
    _icon = "traffic-mirroring.png"
class VpnConnection(_VPC):
    _icon = "vpn-connection.png"
class VpnGateway(_VPC):
    _icon = "vpn-gateway.png"

# Aliases
