# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Lake_Formation(_AWS):
    _type = "analytics/lake_formation"
    _icon_dir = "resources/aws/analytics/lake_formation"


class DataLake(_Lake_Formation):
    _icon = "data-lake.png"

# Aliases
