# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Robomaker(_AWS):
    _type = "robotics/robomaker"
    _icon_dir = "resources/aws/robotics/robomaker"


class CloudExtensionsRos(_Robomaker):
    _icon = "cloud-extensions-ros.png"
class DevelopmentEnvironment(_Robomaker):
    _icon = "development-environment.png"
class FleetManagement(_Robomaker):
    _icon = "fleet-management.png"
class Simulation(_Robomaker):
    _icon = "simulation.png"

# Aliases
