# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Organizations(_AWS):
    _type = "management/organizations"
    _icon_dir = "resources/aws/management/organizations"


class Account(_Organizations):
    _icon = "account.png"
class OrganizationalUnit(_Organizations):
    _icon = "organizational-unit.png"

# Aliases
