# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _DynamoDB(_AWS):
    _type = "database/dynamodb"
    _icon_dir = "resources/aws/database/dynamodb"


class Attribute(_DynamoDB):
    _icon = "attribute.png"
class Attributes(_DynamoDB):
    _icon = "attributes.png"
class DynamoDBAccelerator(_DynamoDB):
    _icon = "dynamodb-accelerator.png"
class GlobalSecondaryIndex(_DynamoDB):
    _icon = "global-secondary-index.png"
class Item(_DynamoDB):
    _icon = "item.png"
class Items(_DynamoDB):
    _icon = "items.png"
class Table(_DynamoDB):
    _icon = "table.png"

# Aliases
