# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OpenStack

class _Lifecyclemanagement/Deployment(_OpenStack):
    _type = "lifecyclemanagement/deployment"
    _icon_dir = "resources/openstack/lifecyclemanagement/deployment"


class Ansible(_Lifecyclemanagement/Deployment):
    _icon = "ansible.png"
class Charms(_Lifecyclemanagement/Deployment):
    _icon = "charms.png"
class Chef(_Lifecyclemanagement/Deployment):
    _icon = "chef.png"
class Helm(_Lifecyclemanagement/Deployment):
    _icon = "helm.png"
class Kolla(_Lifecyclemanagement/Deployment):
    _icon = "kolla.png"
class Tripleo(_Lifecyclemanagement/Deployment):
    _icon = "tripleo.png"

# Aliases
