# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OpenStack

class _Lifecyclemanagement/Packaging(_OpenStack):
    _type = "lifecyclemanagement/packaging"
    _icon_dir = "resources/openstack/lifecyclemanagement/packaging"


class LOCI(_Lifecyclemanagement/Packaging):
    _icon = "loci.png"
class Puppet(_Lifecyclemanagement/Packaging):
    _icon = "puppet.png"
class RPM(_Lifecyclemanagement/Packaging):
    _icon = "rpm.png"

# Aliases
