# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Robotics(_AWS):
    _type = "robotics"
    _icon_dir = "resources/aws/robotics"


class Robomaker(_Robotics):
    _icon = "robomaker.png"

# Aliases
