# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Migration(_AWS):
    _type = "migration"
    _icon_dir = "resources/aws/migration"


class ApplicationDiscoveryService(_Migration):
    _icon = "application-discovery-service.png"
class CloudendureMigration(_Migration):
    _icon = "cloudendure-migration.png"
class DataSync(_Migration):
    _icon = "data-sync.png"
class DatabaseMigration(_Migration):
    _icon = "database-migration.png"
class MigrationHub(_Migration):
    _icon = "migration-hub.png"
class ServerMigrationService(_Migration):
    _icon = "server-migration-service.png"
class TransferFamily(_Migration):
    _icon = "transfer-family.png"

# Aliases

ADS = ApplicationDiscoveryService
CEM = CloudendureMigration
DMS = DatabaseMigration
SMS = ServerMigrationService