# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Sagemaker(_AWS):
    _type = "ml/sagemaker"
    _icon_dir = "resources/aws/ml/sagemaker"


class Model(_Sagemaker):
    _icon = "model.png"
class Notebook(_Sagemaker):
    _icon = "notebook.png"
class Train(_Sagemaker):
    _icon = "train.png"

# Aliases
