# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Arvr(_AWS):
    _type = "arvr"
    _icon_dir = "resources/aws/arvr"


class Sumerian(_Arvr):
    _icon = "sumerian.png"

# Aliases
