# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Database(_AWS):
    _type = "database"
    _icon_dir = "resources/aws/database"


class AuroraInstance(_Database):
    _icon = "aurora-instance.png"
class AuroraMariadbInstanceAlternate(_Database):
    _icon = "aurora-mariadb-instance-alternate.png"
class AuroraMariadbInstance(_Database):
    _icon = "aurora-mariadb-instance.png"
class AuroraMysqlInstanceAlternate(_Database):
    _icon = "aurora-mysql-instance-alternate.png"
class AuroraMysqlInstance(_Database):
    _icon = "aurora-mysql-instance.png"
class AuroraOracleInstanceAlternate(_Database):
    _icon = "aurora-oracle-instance-alternate.png"
class AuroraOracleInstance(_Database):
    _icon = "aurora-oracle-instance.png"
class AuroraPiops(_Database):
    _icon = "aurora-piops.png"
class AuroraPostgresqlInstanceAlternate(_Database):
    _icon = "aurora-postgresql-instance-alternate.png"
class AuroraPostgresqlInstance(_Database):
    _icon = "aurora-postgresql-instance.png"
class AuroraSqlServerInstanceAlternate(_Database):
    _icon = "aurora-sql-server-instance-alternate.png"
class AuroraSqlServerInstance(_Database):
    _icon = "aurora-sql-server-instance.png"
class Aurora(_Database):
    _icon = "aurora.png"
class DatabaseMigration(_Database):
    _icon = "database-migration.png"
class DocumentDB(_Database):
    _icon = "documentdb.png"
class DynamoDB(_Database):
    _icon = "dynamodb.png"
class Elasticache(_Database):
    _icon = "elasticache.png"
class Keyspaces(_Database):
    _icon = "keyspaces.png"
class Neptune(_Database):
    _icon = "neptune.png"
class QuantumLedgerDatabase(_Database):
    _icon = "quantum-ledger-database.png"
class RDSForVmware(_Database):
    _icon = "rds-for-vmware.png"
class RDSProxyAlternate(_Database):
    _icon = "rds-proxy-alternate.png"
class RDSProxy(_Database):
    _icon = "rds-proxy.png"
class RDS(_Database):
    _icon = "rds.png"
class Redshift(_Database):
    _icon = "redshift.png"
class Timestream(_Database):
    _icon = "timestream.png"

# Aliases

DMS = DatabaseMigration
DDB = DynamoDB
ElastiCache = Elasticache
QLDB = QuantumLedgerDatabase