# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Shield(_AWS):
    _type = "security/shield"
    _icon_dir = "resources/aws/security/shield"


class ShieldAdvanced(_Shield):
    _icon = "shield-advanced.png"

# Aliases
