# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Cloudformation(_AWS):
    _type = "management/cloudformation"
    _icon_dir = "resources/aws/management/cloudformation"


class ChangeSet(_Cloudformation):
    _icon = "change-set.png"
class Stack(_Cloudformation):
    _icon = "stack.png"
class Template(_Cloudformation):
    _icon = "template.png"

# Aliases
