# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Cloud9(_AWS):
    _type = "devtools/cloud9"
    _icon_dir = "resources/aws/devtools/cloud9"


class Cloud9(_Cloud9):
    _icon = "cloud9.png"

# Aliases
