# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OpenStack

class _Operations/Billing(_OpenStack):
    _type = "operations/billing"
    _icon_dir = "resources/openstack/operations/billing"


class Cloudkitty(_Operations/Billing):
    _icon = "cloudkitty.png"

# Aliases
