# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OpenStack

class _Operations/Optimization(_OpenStack):
    _type = "operations/optimization"
    _icon_dir = "resources/openstack/operations/optimization"


class Congress(_Operations/Optimization):
    _icon = "congress.png"
class Rally(_Operations/Optimization):
    _icon = "rally.png"
class Vitrage(_Operations/Optimization):
    _icon = "vitrage.png"
class Watcher(_Operations/Optimization):
    _icon = "watcher.png"

# Aliases
