# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _EMR(_AWS):
    _type = "analytics/emr"
    _icon_dir = "resources/aws/analytics/emr"


class Cluster(_EMR):
    _icon = "cluster.png"
class EMREngineMaprM3(_EMR):
    _icon = "emr-engine-mapr-m3.png"
class EMREngineMaprM5(_EMR):
    _icon = "emr-engine-mapr-m5.png"
class EMREngineMaprM7(_EMR):
    _icon = "emr-engine-mapr-m7.png"
class EMREngine(_EMR):
    _icon = "emr-engine.png"
class HdfsCluster(_EMR):
    _icon = "hdfs-cluster.png"

# Aliases
