# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Transfer_Family(_AWS):
    _type = "migration/transfer_family"
    _icon_dir = "resources/aws/migration/transfer_family"


class Ftp(_Transfer_Family):
    _icon = "ftp.png"
class Ftps(_Transfer_Family):
    _icon = "ftps.png"
class Sftp(_Transfer_Family):
    _icon = "sftp.png"

# Aliases
