# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Compute(_AWS):
    _type = "compute"
    _icon_dir = "resources/aws/compute"


class ApplicationAutoScaling(_Compute):
    _icon = "application-auto-scaling.png"
class Batch(_Compute):
    _icon = "batch.png"
class Bottlerocket(_Compute):
    _icon = "bottlerocket.png"
class ComputeOptimizer(_Compute):
    _icon = "compute-optimizer.png"
class EC2AutoScaling(_Compute):
    _icon = "ec2-auto-scaling.png"
class EC2ImageBuilder(_Compute):
    _icon = "ec2-image-builder.png"
class EC2M5N(_Compute):
    _icon = "ec2-m5n.png"
class EC2R5N(_Compute):
    _icon = "ec2-r5n.png"
class EC2(_Compute):
    _icon = "ec2.png"
class ElasticBeanstalk(_Compute):
    _icon = "elastic-beanstalk.png"
class ElasticContainerKubernetes(_Compute):
    _icon = "elastic-container-kubernetes.png"
class ElasticContainerRegistry(_Compute):
    _icon = "elastic-container-registry.png"
class ElasticContainerService(_Compute):
    _icon = "elastic-container-service.png"
class Fargate(_Compute):
    _icon = "fargate.png"
class Lambda(_Compute):
    _icon = "lambda.png"
class Lightsail(_Compute):
    _icon = "lightsail.png"
class LocalZones(_Compute):
    _icon = "local-zones.png"
class NitroEnclaves(_Compute):
    _icon = "nitro-enclaves.png"
class Outposts(_Compute):
    _icon = "outposts.png"
class ParallelCluster(_Compute):
    _icon = "parallel-cluster.png"
class ServerlessApplicationRepository(_Compute):
    _icon = "serverless-application-repository.png"
class ThinkboxDeadline(_Compute):
    _icon = "thinkbox-deadline.png"
class ThinkboxFrost(_Compute):
    _icon = "thinkbox-frost.png"
class ThinkboxKrakatoa(_Compute):
    _icon = "thinkbox-krakatoa.png"
class ThinkboxSequoia(_Compute):
    _icon = "thinkbox-sequoia.png"
class ThinkboxStoke(_Compute):
    _icon = "thinkbox-stoke.png"
class ThinkboxXmesh(_Compute):
    _icon = "thinkbox-xmesh.png"
class VmwareCloudOnAWS(_Compute):
    _icon = "vmware-cloud-on-aws.png"
class Wavelength(_Compute):
    _icon = "wavelength.png"

# Aliases

AutoScaling = ApplicationAutoScaling
ECR = ElasticContainerRegistry
EB = ElasticBeanstalk
ECS = ElasticContainerService
EKS = ElasticContainerKubernetes
SAR = ServerlessApplicationRepository