# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Aurora(_AWS):
    _type = "database/aurora"
    _icon_dir = "resources/aws/database/aurora"


class AuroraInstanceAlternate(_Aurora):
    _icon = "aurora-instance-alternate.png"
class RDSInstanceAternate(_Aurora):
    _icon = "rds-instance-aternate.png"
class RDSInstance(_Aurora):
    _icon = "rds-instance.png"

# Aliases
