# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Lot_Device_Defender(_AWS):
    _type = "iot/lot_device_defender"
    _icon_dir = "resources/aws/iot/lot_device_defender"


class IotDeviceJobs(_Lot_Device_Defender):
    _icon = "iot-device-jobs.png"

# Aliases
