# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Mobile(_AWS):
    _type = "mobile"
    _icon_dir = "resources/aws/mobile"


class AmplifyConsole(_Mobile):
    _icon = "amplify-console.png"
class Appsync(_Mobile):
    _icon = "appsync.png"
class DeviceFarm(_Mobile):
    _icon = "device-farm.png"
class PinpointJourney(_Mobile):
    _icon = "pinpoint-journey.png"
class Pinpoint(_Mobile):
    _icon = "pinpoint.png"

# Aliases
