# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Elastic_Container_Registry(_AWS):
    _type = "containers/elastic_container_registry"
    _icon_dir = "resources/aws/containers/elastic_container_registry"


class Image(_Elastic_Container_Registry):
    _icon = "image.png"
class Registry(_Elastic_Container_Registry):
    _icon = "registry.png"

# Aliases
