# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Iot_Http(_AWS):
    _type = "iot/iot_http"
    _icon_dir = "resources/aws/iot/iot_http"


class Protocol(_Iot_Http):
    _icon = "protocol.png"

# Aliases
