# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OpenStack

class _Adjacentenablers/Containerservices(_OpenStack):
    _type = "adjacentenablers/containerservices"
    _icon_dir = "resources/openstack/adjacentenablers/containerservices"


class Kuryr(_Adjacentenablers/Containerservices):
    _icon = "kuryr.png"

# Aliases
