# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _OpenStack

class _Adjacentenablers/Nfv(_OpenStack):
    _type = "adjacentenablers/nfv"
    _icon_dir = "resources/openstack/adjacentenablers/nfv"


class Tacker(_Adjacentenablers/Nfv):
    _icon = "tacker.png"

# Aliases
