# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Trusted_Advisor(_AWS):
    _type = "management/trusted_advisor"
    _icon_dir = "resources/aws/management/trusted_advisor"


class ChecklistCost(_Trusted_Advisor):
    _icon = "checklist-cost.png"
class ChecklistFaultTolerant(_Trusted_Advisor):
    _icon = "checklist-fault-tolerant.png"
class ChecklistPerformance(_Trusted_Advisor):
    _icon = "checklist-performance.png"
class ChecklistSecurity(_Trusted_Advisor):
    _icon = "checklist-security.png"
class Checklist(_Trusted_Advisor):
    _icon = "checklist.png"

# Aliases
