# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Security_Hub(_AWS):
    _type = "security/security_hub"
    _icon_dir = "resources/aws/security/security_hub"


class Finding(_Security_Hub):
    _icon = "finding.png"

# Aliases
