# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class __Lambda(_AWS):
    _type = "compute/_lambda"
    _icon_dir = "resources/aws/compute/_lambda"


class LambdaFunction(__Lambda):
    _icon = "lambda-function.png"

# Aliases
