# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _System_Manager(_AWS):
    _type = "management/system_manager"
    _icon_dir = "resources/aws/management/system_manager"


class Automation(_System_Manager):
    _icon = "automation.png"
class Documents(_System_Manager):
    _icon = "documents.png"
class Inventory(_System_Manager):
    _icon = "inventory.png"
class MaintenanceWindows(_System_Manager):
    _icon = "maintenance-windows.png"
class Opscenter(_System_Manager):
    _icon = "opscenter.png"
class ParameterStore(_System_Manager):
    _icon = "parameter-store.png"
class PatchManager(_System_Manager):
    _icon = "patch-manager.png"
class RunCommand(_System_Manager):
    _icon = "run-command.png"
class StateManager(_System_Manager):
    _icon = "state-manager.png"

# Aliases
