# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Alexa(_AWS):
    _type = "iot/iot/alexa"
    _icon_dir = "resources/aws/iot/iot/alexa"


class EnabledDevice(_Alexa):
    _icon = "enabled-device.png"
class Skill(_Alexa):
    _icon = "skill.png"
class VoiceService(_Alexa):
    _icon = "voice-service.png"

# Aliases
