# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Elastic_Container_Service(_AWS):
    _type = "containers/elastic_container_service"
    _icon_dir = "resources/aws/containers/elastic_container_service"


class Container1(_Elastic_Container_Service):
    _icon = "container-1.png"
class Container2(_Elastic_Container_Service):
    _icon = "container-2.png"
class Container3(_Elastic_Container_Service):
    _icon = "container-3.png"
class Service(_Elastic_Container_Service):
    _icon = "service.png"
class Task(_Elastic_Container_Service):
    _icon = "task.png"

# Aliases
