# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Opsworks(_AWS):
    _type = "management/opsworks"
    _icon_dir = "resources/aws/management/opsworks"


class Apps(_Opsworks):
    _icon = "apps.png"
class Deployments(_Opsworks):
    _icon = "deployments.png"
class Instances(_Opsworks):
    _icon = "instances.png"
class Layers(_Opsworks):
    _icon = "layers.png"
class Permissions(_Opsworks):
    _icon = "permissions.png"
class Resources(_Opsworks):
    _icon = "resources.png"

# Aliases
