# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Database_Migration_Service(_AWS):
    _type = "database/database_migration_service"
    _icon_dir = "resources/aws/database/database_migration_service"


class DatabaseMigrationWorkflowJob(_Database_Migration_Service):
    _icon = "database-migration-workflow-job.png"

# Aliases
