# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Eventbridge(_AWS):
    _type = "integration/eventbridge"
    _icon_dir = "resources/aws/integration/eventbridge"


class CustomEventBus(_Eventbridge):
    _icon = "custom-event-bus.png"
class DefaultEventBus(_Eventbridge):
    _icon = "default-event-bus.png"

# Aliases
