# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Simple_Storage(_AWS):
    _type = "storage/simple_storage"
    _icon_dir = "resources/aws/storage/simple_storage"


class BucketWithObjects(_Simple_Storage):
    _icon = "bucket-with-objects.png"
class Bucket(_Simple_Storage):
    _icon = "bucket.png"
class GeneralAccessPoints(_Simple_Storage):
    _icon = "general-access-points.png"
class Object(_Simple_Storage):
    _icon = "object.png"
class S3ReplicationTimeControl(_Simple_Storage):
    _icon = "s3-replication-time-control.png"
class S3Replication(_Simple_Storage):
    _icon = "s3-replication.png"
class ServiceGlacierDeepArchive(_Simple_Storage):
    _icon = "service-glacier-deep-archive.png"
class ServiceGlacier(_Simple_Storage):
    _icon = "service-glacier.png"
class ServiceIntelligentTiering(_Simple_Storage):
    _icon = "service-intelligent-tiering.png"
class ServiceOneZoneIa(_Simple_Storage):
    _icon = "service-one-zone-ia.png"
class ServiceStandardIa(_Simple_Storage):
    _icon = "service-standard-ia.png"
class ServiceStandard(_Simple_Storage):
    _icon = "service-standard.png"
class VPCAccessPoints(_Simple_Storage):
    _icon = "vpc-access-points.png"

# Aliases
