# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Iot(_AWS):
    _type = "iot/iot"
    _icon_dir = "resources/aws/iot/iot"


class Action(_Iot):
    _icon = "action.png"
class Actuator(_Iot):
    _icon = "actuator.png"
class Certificate(_Iot):
    _icon = "certificate.png"
class DesiredState(_Iot):
    _icon = "desired-state.png"
class DeviceGateway(_Iot):
    _icon = "device-gateway.png"
class Echo(_Iot):
    _icon = "echo.png"
class Http2Protocol(_Iot):
    _icon = "http2-protocol.png"
class OverAirUpdate(_Iot):
    _icon = "over-air-update.png"
class Policy(_Iot):
    _icon = "policy.png"
class ReportedState(_Iot):
    _icon = "reported-state.png"
class Sensor(_Iot):
    _icon = "sensor.png"
class Servo(_Iot):
    _icon = "servo.png"
class Shadow(_Iot):
    _icon = "shadow.png"
class Simulator(_Iot):
    _icon = "simulator.png"
class Topic(_Iot):
    _icon = "topic.png"

# Aliases
