# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _WAF(_AWS):
    _type = "security/waf"
    _icon_dir = "resources/aws/security/waf"


class FilteringRule(_WAF):
    _icon = "filtering-rule.png"

# Aliases
