# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Elastic_Load_Balancing(_AWS):
    _type = "network/elastic_load_balancing"
    _icon_dir = "resources/aws/network/elastic_load_balancing"


class ApplicationLoadBalancer(_Elastic_Load_Balancing):
    _icon = "application-load-balancer.png"
class ClassicLoadBalancer(_Elastic_Load_Balancing):
    _icon = "classic-load-balancer.png"
class NetworkLoadBalancer(_Elastic_Load_Balancing):
    _icon = "network-load-balancer.png"

# Aliases
