# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Management(_AWS):
    _type = "management"
    _icon_dir = "resources/aws/management"


class AppConfig(_Management):
    _icon = "app-config.png"
class AppWizard(_Management):
    _icon = "app-wizard.png"
class AutoScaling(_Management):
    _icon = "auto-scaling.png"
class BackintAgent(_Management):
    _icon = "backint-agent.png"
class Chatbot(_Management):
    _icon = "chatbot.png"
class CloudTrail(_Management):
    _icon = "cloud-trail.png"
class Cloudformation(_Management):
    _icon = "cloudformation.png"
class Cloudwatch(_Management):
    _icon = "cloudwatch.png"
class CommandLineInterface(_Management):
    _icon = "command-line-interface.png"
class ComputeOptimizer(_Management):
    _icon = "compute-optimizer.png"
class Config(_Management):
    _icon = "config.png"
class ControlTower(_Management):
    _icon = "control-tower.png"
class LicenseManager(_Management):
    _icon = "license-manager.png"
class ManagedServices(_Management):
    _icon = "managed-services.png"
class ManagementConsole(_Management):
    _icon = "management-console.png"
class OpsworksMonitoring(_Management):
    _icon = "opsworks-monitoring.png"
class OpsworksStack2(_Management):
    _icon = "opsworks-stack2.png"
class Opsworks(_Management):
    _icon = "opsworks.png"
class Organizations(_Management):
    _icon = "organizations.png"
class PersonalHealthDashboard(_Management):
    _icon = "personal-health-dashboard.png"
class ServiceCatalog(_Management):
    _icon = "service-catalog.png"
class SystemsManager(_Management):
    _icon = "systems-manager.png"
class TrustedAdvisor(_Management):
    _icon = "trusted-advisor.png"
class WellArchitectTool(_Management):
    _icon = "well-architect-tool.png"

# Aliases

SSM = SystemsManager