# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Glue(_AWS):
    _type = "analytics/glue"
    _icon_dir = "resources/aws/analytics/glue"


class Crawler(_Glue):
    _icon = "crawler.png"
class DataCatalog(_Glue):
    _icon = "data-catalog.png"

# Aliases
