# This module is automatically generated by autogen.sh. DO NOT EDIT.

from .. import _AWS

class _Simple_Queue_Service(_AWS):
    _type = "integration/simple_queue_service"
    _icon_dir = "resources/aws/integration/simple_queue_service"


class Message(_Simple_Queue_Service):
    _icon = "message.png"
class Queue(_Simple_Queue_Service):
    _icon = "queue.png"

# Aliases
